version: 2
jobs:
  build:
    docker:
      - image: circleci/golang

    working_directory: /go/src/github.com/cv/sd

    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure
      - run: make clean build
