version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/cv/sd
    steps:
      - checkout
      - deploy:
          name: goreleaser
          command: |
            curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  tagged-builds:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
