version: 2

workflows:
  version: 2
  release-tag:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

jobs:
  release:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/cv/sd
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: |
            sudo apt-get install -y rpm
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
      - setup_remote_docker:
          docker_layer_caching: true
      - deploy:
          name: goreleaser
          command: |
            echo $DOCKER_PASSWORD | docker login -u cvillela --password-stdin
            curl -sL https://git.io/goreleaser | bash
